name: acceptance-test

on:
  pull_request:
    paths:
      - .github/workflows/acceptance-test.yaml
      - '**.go'
      - go.*
      - acceptance_test/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/acceptance-test.yaml
      - '**.go'
      - go.*
      - acceptance_test/**

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true

      - uses: flatt-security/setup-takumi-guard-golang@2e3c7c40b538cd68b2ac483def12982ebc8bc02e # v1
        with:
          bot-id: ${{secrets.TAKUMI_GUARD_BOT_ID}}

      - run: go build -ldflags '-X main.version=${{ github.ref_name }}'
      - run: make -C acceptance_test
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: make -C acceptance_test clean-up
        if: always()
        env:
          GITHUB_TOKEN: ${{ github.token }}
